var feedContent1 = [{
        "AD_SIZE": "300x600",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "create laugh <unique>CROCS</unique> style color dream comfort love charm",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_ClassicClog_FullBody_ModelImage_Zooey.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "PRODUCT_NAME": "Classic Clog|#F1718B",
        "OFFER_ID": "Onfig_1"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "write dance <unique>sing</unique> color play inspire create direct act",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_CrocbandClog_FullBodyModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "PRODUCT_NAME": "Crocband™ Clog|#F69687",
        "OFFER_ID": "Onfig_2"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "pool vacation <unique>spring</unique> escape relax flip weekend sunset chill",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_CrocbandFlip_FullBody_ModelImage_Zooey.png",
        "IMAGE_URL4": "300x600_CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "300x600_CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "PRODUCT_NAME": "Crocband™ Flip|#EF4050",
        "OFFER_ID": "Onfig_3"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "excite dazzle <unique>style</unique> romance escape summer arrive relax dance",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_CrocsSerenaSandal_FullBodynaSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "300x600_CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "300x600_CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "PRODUCT_NAME": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": "Onfig_4"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "evolve calm <unique>chill</unique> yoga comfort rebound float soothe move",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_LiteRideClog_FullBody_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "PRODUCT_NAME": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": "Onfig_5"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "right",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "weekend express <unique>amaze</unique> style stretch explore bounce innovate relax",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_LiteRideSandal_FullBody_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "PRODUCT_NAME": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": "Onfig_6"
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "left",
        "TEXT_5": "SHOP NOW",
        "PROMOTIONAL_COPY": "splash float <unique>play</unique> relax getaway delight beach travel swim",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL3": "300x600_SwiftwaterSandal_FullBody_ModelImage_Zooey.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "PRODUCT_NAME": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": "Onfig_7"
    }
];
var feedContent = [{
        "AD_SIZE": "160x600",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_ClassicClog_evenRowsImage.png",
        "IMAGE_URL2": "160x600_ClassicClog_oddRowsImage.png",
        "IMAGE_URL3": "160x600_ClassicClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 1
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_CrocbandClog_evenRowsImage.png",
        "IMAGE_URL2": "160x600_CrocbandClog_oddRowsImage.png",
        "IMAGE_URL3": "160x600_CrocbandClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 2
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_CrocbandFlip_evenRowsImage.png",
        "IMAGE_URL2": "160x600_CrocbandFlip_oddRowsImage.png",
        "IMAGE_URL3": "160x600_CrocbandFlip_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 3
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_CrocsSerenaSandal_evenRowsImage.png",
        "IMAGE_URL2": "160x600_CrocsSerenaSandal_oddRowsImage.png",
        "IMAGE_URL3": "160x600_CrocsSerenaSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 4
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_LiteRideClog_evenRowsImage.png",
        "IMAGE_URL2": "160x600_LiteRideClog_oddRowsImage.png",
        "IMAGE_URL3": "160x600_LiteRideClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 5
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_LiteRideSandal_evenRowsImage.png",
        "IMAGE_URL2": "160x600_LiteRideSandal_oddRowsImage.png",
        "IMAGE_URL3": "160x600_LiteRideSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 6
    },
    {
        "AD_SIZE": "160x600",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "160x600_SwiftwaterSandal_evenRowsImage.png",
        "IMAGE_URL2": "160x600_SwiftwaterSandal_oddRowsImage.png",
        "IMAGE_URL3": "160x600_SwiftwaterSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 7
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_ClassicClog_evenRowsImage.png",
        "IMAGE_URL2": "300x250_ClassicClog_oddRowsImage.png",
        "IMAGE_URL3": "300x250_ClassicClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 8
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_CrocbandClog_evenRowsImage.png",
        "IMAGE_URL2": "300x250_CrocbandClog_oddRowsImage.png",
        "IMAGE_URL3": "300x250_CrocbandClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 9
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_CrocbandFlip_evenRowsImage.png",
        "IMAGE_URL2": "300x250_CrocbandFlip_oddRowsImage.png",
        "IMAGE_URL3": "300x250_CrocbandFlip_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 10
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_CrocsSerenaSandal_evenRowsImage.png",
        "IMAGE_URL2": "300x250_CrocsSerenaSandal_oddRowsImage.png",
        "IMAGE_URL3": "300x250_CrocsSerenaSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 11
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_LiteRideClog_evenRowsImage.png",
        "IMAGE_URL2": "300x250_LiteRideClog_oddRowsImage.png",
        "IMAGE_URL3": "300x250_LiteRideClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 12
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_LiteRideSandal_evenRowsImage.png",
        "IMAGE_URL2": "300x250_LiteRideSandal_oddRowsImage.png",
        "IMAGE_URL3": "300x250_LiteRideSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 13
    },
    {
        "AD_SIZE": "300x250",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x250_SwiftwaterSandal_evenRowsImage.png",
        "IMAGE_URL2": "300x250_SwiftwaterSandal_oddRowsImage.png",
        "IMAGE_URL3": "300x250_SwiftwaterSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 14
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_ClassicClog_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_ClassicClog_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_ClassicClog_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 15
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_CrocbandClog_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_CrocbandClog_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_CrocbandClog_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 16
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_CrocbandFlip_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_CrocbandFlip_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_CrocbandFlip_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "300x600_CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "300x600_CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 17
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_CrocsSerenaSandal_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_CrocsSerenaSandal_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_CrocsSerenaSandal_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "300x600_CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "300x600_CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 18
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_LiteRideClog_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_LiteRideClog_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_LiteRideClog_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 19
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_LiteRideSandal_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_LiteRideSandal_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_LiteRideSandal_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 20
    },
    {
        "AD_SIZE": "300x600",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "NA",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "300x600_SwiftwaterSandal_Portrait_evenRowsImage.png",
        "IMAGE_URL2": "300x600_SwiftwaterSandal_Portrait_oddRowsImage.png",
        "IMAGE_URL3": "300x600_SwiftwaterSandal_Portrait_ModelImage_Zooey.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 21
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_ClassicClog_evenRowsImage.png",
        "IMAGE_URL2": "728x90_ClassicClog_oddRowsImage.png",
        "IMAGE_URL3": "728x90_ClassicClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_ClassicClog_ProductImage.png",
        "IMAGE_URL5": "728x90_ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 22
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_CrocbandClog_evenRowsImage.png",
        "IMAGE_URL2": "728x90_CrocbandClog_oddRowsImage.png",
        "IMAGE_URL3": "728x90_CrocbandClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "728x90_CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 23
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_CrocbandFlip_evenRowsImage.png",
        "IMAGE_URL2": "728x90_CrocbandFlip_oddRowsImage.png",
        "IMAGE_URL3": "728x90_CrocbandFlip_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "728x90_CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 24
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_CrocsSerenaSandal_evenRowsImage.png",
        "IMAGE_URL2": "728x90_CrocsSerenaSandal_oddRowsImage.png",
        "IMAGE_URL3": "728x90_CrocsSerenaSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "728x90_CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 25
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_LiteRideClog_evenRowsImage.png",
        "IMAGE_URL2": "728x90_LiteRideClog_oddRowsImage.png",
        "IMAGE_URL3": "728x90_LiteRideClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "728x90_LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 26
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_LiteRideSandal_evenRowsImage.png",
        "IMAGE_URL2": "728x90_LiteRideSandal_oddRowsImage.png",
        "IMAGE_URL3": "728x90_LiteRideSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "728x90_LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 27
    },
    {
        "AD_SIZE": "728x90",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "728x90_SwiftwaterSandal_evenRowsImage.png",
        "IMAGE_URL2": "728x90_SwiftwaterSandal_oddRowsImage.png",
        "IMAGE_URL3": "728x90_SwiftwaterSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "728x90_SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "728x90_SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 28
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_ClassicClog_evenRowsImage.png",
        "IMAGE_URL2": "970x250_ClassicClog_oddRowsImage.png",
        "IMAGE_URL3": "970x250_ClassicClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 29
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_CrocbandClog_evenRowsImage.png",
        "IMAGE_URL2": "970x250_CrocbandClog_oddRowsImage.png",
        "IMAGE_URL3": "970x250_CrocbandClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 30
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_CrocbandFlip_evenRowsImage.png",
        "IMAGE_URL2": "970x250_CrocbandFlip_oddRowsImage.png",
        "IMAGE_URL3": "970x250_CrocbandFlip_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 31
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_CrocsSerenaSandal_evenRowsImage.png",
        "IMAGE_URL2": "970x250_CrocsSerenaSandal_oddRowsImage.png",
        "IMAGE_URL3": "970x250_CrocsSerenaSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 32
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_LiteRideClog_evenRowsImage.png",
        "IMAGE_URL2": "970x250_LiteRideClog_oddRowsImage.png",
        "IMAGE_URL3": "970x250_LiteRideClog_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 33
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_LiteRideSandal_evenRowsImage.png",
        "IMAGE_URL2": "970x250_LiteRideSandal_oddRowsImage.png",
        "IMAGE_URL3": "970x250_LiteRideSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 34
    },
    {
        "AD_SIZE": "970x250",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "970x250_SwiftwaterSandal_evenRowsImage.png",
        "IMAGE_URL2": "970x250_SwiftwaterSandal_oddRowsImage.png",
        "IMAGE_URL3": "970x250_SwiftwaterSandal_ModelImage_Zooey.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 35
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "Classic Clog",
        "TEXT_2": "ClassicClog",
        "TEXT_3": "I crocs.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "ClassicClog_ProductImage.png",
        "IMAGE_URL5": "ClassicClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Classic Clog|#F1718B",
        "OFFER_ID": 36
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "Crocband™ Clog",
        "TEXT_2": "CrocbandClog",
        "TEXT_3": "I sing.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "CrocbandClog_ProductImage.png",
        "IMAGE_URL5": "CrocbandClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Clog|#F69687",
        "OFFER_ID": 37
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "Crocband™ Flip",
        "TEXT_2": "CrocbandFlip",
        "TEXT_3": "I spring.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "CrocbandFlip_ProductImage.png",
        "IMAGE_URL5": "CrocbandFlip_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocband™ Flip|#EF4050",
        "OFFER_ID": 38
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "Crocs Serena Sandal",
        "TEXT_2": "CrocsSerenaSandal",
        "TEXT_3": "I style.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "CrocsSerenaSandal_ProductImage.png",
        "IMAGE_URL5": "CrocsSerenaSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Crocs Serena Sandal|#DBAF3C",
        "OFFER_ID": 39
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "LiteRide™ Clog",
        "TEXT_2": "LiteRideClog",
        "TEXT_3": "I chill.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "LiteRideClog_ProductImage.png",
        "IMAGE_URL5": "LiteRideClog_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Clog|#2F478C",
        "OFFER_ID": 40
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "LiteRide™ Sandal",
        "TEXT_2": "LiteRideSandal",
        "TEXT_3": "I amaze.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "LiteRideSandal_ProductImage.png",
        "IMAGE_URL5": "LiteRideSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "LiteRide™ Sandal|#00ACA4",
        "OFFER_ID": 41
    },
    {
        "AD_SIZE": "320x50",
        "TEXT_1": "Swiftwater™ Sandal",
        "TEXT_2": "SwiftwaterSandal",
        "TEXT_3": "I play.",
        "TEXT_4": "Zooey Deschanel<br><font class='proximaNovaItalic'>Entertainer</font>",
        "TEXT_5": "SHOP NOW",
        "IMAGE_URL": "1x1.png",
        "IMAGE_URL1": "1x1.png",
        "IMAGE_URL2": "1x1.png",
        "IMAGE_URL3": "1x1.png",
        "IMAGE_URL4": "SwiftwaterSandal_ProductImage.png",
        "IMAGE_URL5": "SwiftwaterSandal_ProductImage_Shadow.png",
        "PROVIDER_CATEGORY": "Swiftwater™ Sandal|#F1718B",
        "OFFER_ID": 42
    }
];
